### ISSUE TITLE
Track Python-bindings improvements

### ISSUE THREAD

**Issue by commial** [ANSSI-FR/MLA#193]
With #190, an initial Python support is provided.

It is still in its early days, and the API might change a lot.

This issue is used to track the futures improvements and associated limitations.

## TODO

- [ ]  for writing mode, `.finalize` can be called on `Drop` to allow for an easier usage.
  - :warning: `.finalize` can't be called twice, otherwise a MLA error will be raised. The Python API can wrap it on `Drop`, allowing the user to either call it or not
- [ ] support writing chunks to multiple file. A basic implementation would be the direct wrapping of `start_file`, `add_file_content` and `end_file`
- [ ] support for `linear_extract` wrapping. This could be made using a Python callback, or a given interface (as a Python abstract class) to derive
- [ ] add basic examples to a `examples/` directory, and tests them
- [ ] add a README and document usage
- [ ] add build & test instructions (based on `maturin` and `pytest`)

## Known caveats

- For now, `MLA` structures are not `Sync`. As a result, a reference on an archive cannot transit between Threads (but they are `Send`, so the struct itself can)
- A design change is likely required before having a Python object standing for a file in the Archive. Such an object would ease a more Pythonic interface, with a `io.BufferedIO` derived class.

**Comment by extiop** [comment]
Known caveats adressed in https://github.com/ANSSI-FR/MLA/pull/258 by using Mutex and latest pyo3 releases.

**Comment by extiop** [comment]
Great improvement with https://github.com/ANSSI-FR/MLA/pull/362/commits/eb257d2a3bd70009acbe80570ea44ad52865ca2a + https://github.com/ANSSI-FR/MLA/pull/364
